name: Maven Build and Docker Push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Check Java Version
        run: java -version
      - name: Check Maven Version
        run: mvn -version
      - name: Maven compile
        run: mvn compile
      - name: Maven Test
        run: mvn test
      - name: Maven clean package
        run: mvn package -DskipTests
      - name: Check JAR File
        run: ls -lh target/
      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        if: github.event_name == 'push'
        run: |
          docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/maven-demo:${{ github.run_number }} \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/maven-demo:latest \
          .
      - name: Check Docker Images
        if: github.event_name == 'push'
        run: docker images
      - name: Push Version Image
        if: github.event_name == 'push'
        run: |
          docker push \
          ${{ secrets.DOCKERHUB_USERNAME }}/maven-demo:${{ github.run_number }}
      - name: Push Latest Image
        if: github.event_name == 'push'
        run: |
          docker push \
          ${{ secrets.DOCKERHUB_USERNAME }}/maven-demo:latest